# Generated by Django 4.2.2 on 2023-06-14 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField(max_length=1000000)),
                (
                    "datetime",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("user", models.TextField(max_length=100000)),
            ],
        ),
    ]
