# Generated by Django 4.2.2 on 2023-06-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                (
                    "nickname",
                    models.CharField(default="default value", max_length=1000),
                ),
                ("email", models.CharField(max_length=1000)),
                ("dob", models.DateTimeField(max_length=100)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, upload_to="profile_pics/"),
                ),
                ("twitter", models.URLField(default="default value", max_length=1000)),
                ("github", models.URLField(default="default value", max_length=1000)),
                ("userid", models.TextField(max_length=100)),
            ],
        ),
    ]
