# Generated by Django 4.2.2 on 2023-06-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_personal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="static/"),
        ),
    ]
