# Generated by Django 4.2.2 on 2023-06-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0008_alter_personal_profile_pic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Personal",
        ),
    ]
